// Code generated from PocketMine-MP generated/YmlServerProperties.php; DO NOT EDIT.

package server

// Keys of pocketmine.yml, a port of pocketmine\YmlServerProperties (Yml + the constant name in
// CamelCase).
const (
	YmlAliases                              = "aliases"
	YmlAnonymousStatistics                  = "anonymous-statistics"
	YmlAnonymousStatisticsEnabled           = "anonymous-statistics.enabled"
	YmlAnonymousStatisticsHost              = "anonymous-statistics.host"
	YmlAutoReport                           = "auto-report"
	YmlAutoReportEnabled                    = "auto-report.enabled"
	YmlAutoReportHost                       = "auto-report.host"
	YmlAutoReportSendCode                   = "auto-report.send-code"
	YmlAutoReportSendPhpinfo                = "auto-report.send-phpinfo"
	YmlAutoReportSendSettings               = "auto-report.send-settings"
	YmlAutoReportUseHttps                   = "auto-report.use-https"
	YmlAutoUpdater                          = "auto-updater"
	YmlAutoUpdaterEnabled                   = "auto-updater.enabled"
	YmlAutoUpdaterHost                      = "auto-updater.host"
	YmlAutoUpdaterOnUpdate                  = "auto-updater.on-update"
	YmlAutoUpdaterOnUpdateWarnConsole       = "auto-updater.on-update.warn-console"
	YmlAutoUpdaterPreferredChannel          = "auto-updater.preferred-channel"
	YmlAutoUpdaterSuggestChannels           = "auto-updater.suggest-channels"
	YmlChunkGeneration                      = "chunk-generation"
	YmlChunkGenerationPopulationQueueSize   = "chunk-generation.population-queue-size"
	YmlChunkSending                         = "chunk-sending"
	YmlChunkSendingPerTick                  = "chunk-sending.per-tick"
	YmlChunkSendingSpawnRadius              = "chunk-sending.spawn-radius"
	YmlChunkTicking                         = "chunk-ticking"
	YmlChunkTickingBlocksPerSubchunkPerTick = "chunk-ticking.blocks-per-subchunk-per-tick"
	YmlChunkTickingDisableBlockTicking      = "chunk-ticking.disable-block-ticking"
	YmlChunkTickingTickRadius               = "chunk-ticking.tick-radius"
	YmlConsole                              = "console"
	YmlConsoleEnableInput                   = "console.enable-input"
	YmlConsoleTitleTick                     = "console.title-tick"
	YmlDebug                                = "debug"
	YmlDebugLevel                           = "debug.level"
	YmlLevelSettings                        = "level-settings"
	YmlLevelSettingsDefaultFormat           = "level-settings.default-format"
	YmlMemory                               = "memory"
	YmlMemoryAsyncWorkerHardLimit           = "memory.async-worker-hard-limit"
	YmlMemoryCheckRate                      = "memory.check-rate"
	YmlMemoryContinuousTrigger              = "memory.continuous-trigger"
	YmlMemoryContinuousTriggerRate          = "memory.continuous-trigger-rate"
	YmlMemoryGarbageCollection              = "memory.garbage-collection"
	YmlMemoryGarbageCollectionPeriod        = "memory.garbage-collection.period"
	YmlMemoryGlobalLimit                    = "memory.global-limit"
	YmlMemoryMainHardLimit                  = "memory.main-hard-limit"
	YmlMemoryMainLimit                      = "memory.main-limit"
	YmlMemoryMaxChunks                      = "memory.max-chunks"
	YmlMemoryMaxChunksChunkRadius           = "memory.max-chunks.chunk-radius"
	YmlMemoryMemoryDump                     = "memory.memory-dump"
	YmlMemoryMemoryDumpDumpAsyncWorker      = "memory.memory-dump.dump-async-worker"
	YmlNetwork                              = "network"
	YmlNetworkAsyncCompression              = "network.async-compression"
	YmlNetworkAsyncCompressionThreshold     = "network.async-compression-threshold"
	YmlNetworkBatchThreshold                = "network.batch-threshold"
	YmlNetworkCompressionLevel              = "network.compression-level"
	YmlNetworkEnableEncryption              = "network.enable-encryption"
	YmlNetworkMaxMtuSize                    = "network.max-mtu-size"
	YmlNetworkUpnpForwarding                = "network.upnp-forwarding"
	YmlPlayer                               = "player"
	YmlPlayerSavePlayerData                 = "player.save-player-data"
	YmlPlayerVerifyXuid                     = "player.verify-xuid"
	YmlPlugins                              = "plugins"
	YmlPluginsLegacyDataDir                 = "plugins.legacy-data-dir"
	YmlSettings                             = "settings"
	YmlSettingsAsyncWorkers                 = "settings.async-workers"
	YmlSettingsEnableDevBuilds              = "settings.enable-dev-builds"
	YmlSettingsEnableProfiling              = "settings.enable-profiling"
	YmlSettingsForceLanguage                = "settings.force-language"
	YmlSettingsProfileReportTrigger         = "settings.profile-report-trigger"
	YmlSettingsQueryPlugins                 = "settings.query-plugins"
	YmlSettingsShutdownMessage              = "settings.shutdown-message"
	YmlTicksPer                             = "ticks-per"
	YmlTicksPerAutosave                     = "ticks-per.autosave"
	YmlTimings                              = "timings"
	YmlTimingsHost                          = "timings.host"
	YmlWorlds                               = "worlds"
)
