package convert

import "pocketmine-go/pocketmine/item"

// coreItemConstructors is the item side of ItemSerializerDeserializerRegistrar's deserializers for
// the item types itemTypeNames maps: item type ID => the VanillaItems getter creating it. The music
// discs are added from item.VanillaRecords() in init().
var coreItemConstructors = map[int]func() item.Item{
	item.INK_SAC:                item.VanillaInkSac,
	item.IRON_INGOT:             item.VanillaIronIngot,
	item.ARROW:                  item.VanillaArrow,
	item.EGG:                    item.VanillaEgg,
	item.SNOWBALL:               item.VanillaSnowball,
	item.ICE_BOMB:               item.VanillaIceBomb,
	item.ENDER_PEARL:            item.VanillaEnderPearl,
	item.EXPERIENCE_BOTTLE:      item.VanillaExperienceBottle,
	item.PAINTING:               item.VanillaPainting,
	item.END_CRYSTAL:            item.VanillaEndCrystal,
	item.ZOMBIE_SPAWN_EGG:       item.VanillaZombieSpawnEgg,
	item.SQUID_SPAWN_EGG:        item.VanillaSquidSpawnEgg,
	item.VILLAGER_SPAWN_EGG:     item.VanillaVillagerSpawnEgg,
	item.APPLE:                  item.VanillaApple,
	item.BAKED_POTATO:           item.VanillaBakedPotato,
	item.BEETROOT_SEEDS:         item.VanillaBeetrootSeeds,
	item.BEETROOT_SOUP:          item.VanillaBeetrootSoup,
	item.BLAZE_ROD:              item.VanillaBlazeRod,
	item.BONE_MEAL:              item.VanillaBoneMeal,
	item.BOOK:                   item.VanillaBook,
	item.BOW:                    item.VanillaBow,
	item.BOWL:                   item.VanillaBowl,
	item.BREAD:                  item.VanillaBread,
	item.BUCKET:                 item.VanillaBucket,
	item.CARROT:                 item.VanillaCarrot,
	item.CHARCOAL:               item.VanillaCharcoal,
	item.CLOCK:                  item.VanillaClock,
	item.COAL:                   item.VanillaCoal,
	item.COCOA_BEANS:            item.VanillaCocoaBeans,
	item.COMPASS:                item.VanillaCompass,
	item.COOKED_CHICKEN:         item.VanillaCookedChicken,
	item.COOKED_FISH:            item.VanillaCookedFish,
	item.COOKED_MUTTON:          item.VanillaCookedMutton,
	item.COOKED_PORKCHOP:        item.VanillaCookedPorkchop,
	item.COOKED_RABBIT:          item.VanillaCookedRabbit,
	item.COOKED_SALMON:          item.VanillaCookedSalmon,
	item.COOKIE:                 item.VanillaCookie,
	item.DRIED_KELP:             item.VanillaDriedKelp,
	item.DYE:                    item.VanillaDye,
	item.ENCHANTED_BOOK:         item.VanillaEnchantedBook,
	item.ENCHANTED_GOLDEN_APPLE: item.VanillaEnchantedGoldenApple,
	item.FIREWORK_STAR:          item.VanillaFireworkStar,
	item.FISHING_ROD:            item.VanillaFishingRod,
	item.FLINT_AND_STEEL:        item.VanillaFlintAndSteel,
	item.GLASS_BOTTLE:           item.VanillaGlassBottle,
	item.GLOW_BERRIES:           item.VanillaGlowBerries,
	item.GOAT_HORN:              item.VanillaGoatHorn,
	item.GOLDEN_APPLE:           item.VanillaGoldenApple,
	item.GOLDEN_CARROT:          item.VanillaGoldenCarrot,
	item.HONEY_BOTTLE:           item.VanillaHoneyBottle,
	item.LINGERING_POTION:       item.VanillaLingeringPotion,
	item.MEDICINE:               item.VanillaMedicine,
	item.MELON_SEEDS:            item.VanillaMelonSeeds,
	item.MILK_BUCKET:            item.VanillaMilkBucket,
	item.MINECART:               item.VanillaMinecart,
	item.MUSHROOM_STEW:          item.VanillaMushroomStew,
	item.PITCHER_POD:            item.VanillaPitcherPod,
	item.POISONOUS_POTATO:       item.VanillaPoisonousPotato,
	item.POTATO:                 item.VanillaPotato,
	item.POTION:                 item.VanillaPotion,
	item.PUFFERFISH:             item.VanillaPufferfish,
	item.PUMPKIN_PIE:            item.VanillaPumpkinPie,
	item.PUMPKIN_SEEDS:          item.VanillaPumpkinSeeds,
	item.RABBIT_STEW:            item.VanillaRabbitStew,
	item.RAW_BEEF:               item.VanillaRawBeef,
	item.RAW_CHICKEN:            item.VanillaRawChicken,
	item.RAW_FISH:               item.VanillaRawFish,
	item.RAW_MUTTON:             item.VanillaRawMutton,
	item.RAW_PORKCHOP:           item.VanillaRawPorkchop,
	item.RAW_RABBIT:             item.VanillaRawRabbit,
	item.RAW_SALMON:             item.VanillaRawSalmon,
	item.REDSTONE_DUST:          item.VanillaRedstoneDust,
	item.ROTTEN_FLESH:           item.VanillaRottenFlesh,
	item.SHEARS:                 item.VanillaShears,
	item.SPIDER_EYE:             item.VanillaSpiderEye,
	item.SPLASH_POTION:          item.VanillaSplashPotion,
	item.SPYGLASS:               item.VanillaSpyglass,
	item.STEAK:                  item.VanillaSteak,
	item.STICK:                  item.VanillaStick,
	item.STRING:                 item.VanillaString,
	item.SUSPICIOUS_STEW:        item.VanillaSuspiciousStew,
	item.SWEET_BERRIES:          item.VanillaSweetBerries,
	item.TORCHFLOWER_SEEDS:      item.VanillaTorchflowerSeeds,
	item.TOTEM:                  item.VanillaTotem,
	item.TRIDENT:                item.VanillaTrident,
	item.WHEAT_SEEDS:            item.VanillaWheatSeeds,
	item.WRITABLE_BOOK:          item.VanillaWritableBook,
	item.WRITTEN_BOOK:           item.VanillaWrittenBook,
}

func init() {
	for _, record := range item.VanillaRecords() {
		r := record
		coreItemConstructors[r.GetTypeId()] = func() item.Item { return r.Clone() }
	}
}
