// Package populator is a port of a slice of pocketmine\world\generator\populator: the pass that
// decorates a chunk's terrain (already generated by a Generator) with scattered features - tall
// grass, ore veins, trees, ... - after the base shape exists.
package populator

import (
	"pocketmine-go/pocketmine/block"
	"pocketmine-go/pocketmine/utils"
)

// Populator is a port of the Populator interface. Its real PHP signature takes a ChunkManager;
// block.World already exposes the exact surface (GetBlockAt/SetBlock/GetOrLoadChunkAtPosition)
// a populator needs, so it's used directly here rather than declaring a narrower local interface
// - block doesn't import world/generator/populator, so there's no cycle risk in doing so.
type Populator interface {
	Populate(world block.World, chunkX, chunkZ int, random *utils.Random)
}
